name: GreenArrow Sync to D1

# Настраиваем триггеры (когда запускать скрипт)
on:
  # 1. Запуск по расписанию (Cron)
  # Сейчас стоит запуск каждый час в 00 минут. 
  # Если хочешь раз в 6 часов, поменяй на: "0 */6 * * *"
  schedule:
    - cron: "0 * * * *"
  
  # 2. Позволяет запускать скрипт вручную прямо из интерфейса GitHub (очень полезно для тестов!)
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest

steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Заставляет сами экшены GitHub использовать новую версию
        with:
          node-version: '24' # Меняем 20 на 24

      - name: Run Sync Script
        run: node sync.js